#+TITLE: 人和电脑
#+SETUPFILE: css/level-1.css
#+DATE: <2014-04-27 日>

* 电脑究竟给我带来了什么？

** 沟通的便捷？
我几乎不上qq了，gtalk上可以聊的人就一个。即使登上了qq也是挂着不聊。

** 查资料？
是的，我很多情况下需要用电脑找文献，但是找文献太容易把我的注意力分散到其他地方，
而其他地方一晃就几个小时，机械性的，不知疲倦。

** 问问题？
比如啦email 问别人问题，或者stackexchange 上问问题。这听起来挺不错的，但是仔细
想想组织问题的时间以及查阅别人回答的时间和自己解决这个问题所花的时间哪个多？弄
懂这个问题所带来的收获有多大？这问题能否放在一边儿，问题多的是，为什么强迫症似的
纠结在一个上面？过一段时间再来看这个问题可能已经变得很容易了。

** 写程序
好久没见我写程序了，k&r 也只看了四分之一。总之需要动脑子的事情绝对不是在电脑上
做的，在电脑上做的事情都是机械的，不能够提升自己能力的事情。

** Linux 让我...
大家都说linux好，我也说好。我用起来也能体会到很多它带来的便捷，可是呢？linux是不
是一个奴役人的工具？那么多狂热的追随者，已经忘了用linux使自己能力提升，而是仅仅
追求一些表面的东西，比如说桌面效果啦；设置软件快捷键啦；调整配四模式啦；以及让菜
单不见啦，显示行号啦。这些全是怪癖！我说这些其实是不许要的，有人说弄好以后会使你
的工作效率提升很多，我看不见得，很多情况下只是个人的强迫症罢了。你配置这些东西的
时间可以让你学习一些更基础的理论知识，而不是只是上网找别人配好的代码放在自己的配置
文件当中。这让我想到了以前网上流传的qq空间代码，让qq空间变得好看，我快和非主流看齐
了。

所以抛弃自己的怪癖吧，把时间花在更理论层面的地方，RTMF虽然这个词我不喜欢，但是自己
静下心来读文档也比自己在网上乱晃google强。 

** 我要限制自己用电脑的时间
我已经发现一半的我已经成为了电脑的 *奴隶*，我看到电脑我就想打开，打开了电脑我就去点
浏览器，点开了浏览器我就去我常去的那几个网站，转一转。接下来再看看系统有没有升级
更新？检查一下，升级。有时候看着电脑这个软件怎么不漂亮，配置一下。打开gtalk看看谁
在线？再看看自己的邮箱，有没有邮件。到快睡觉或者快吃饭的时候，或自己要求自己赶快
关掉电脑的时候，自己又对自己说，等一下，看完这个就关。每天都是这样。虽然我掌握着
关掉电脑电源的权利，但是电脑即使在它断电的情况下也对我的大脑进行着控制，我难道不是
它的奴隶？

从今天起，我每天用电脑的时间只能是下午和晚上睡觉前一小时，其他时间一律不能碰
电脑。 我要把我从电脑中解救出来，让它成为我的奴隶！

** 好久没有写博客了
好久没写博客了，今天写写，发发牢骚，发发感想。生活和科研的压力实在太大了，我得管住
自己。而且，我学的org-mode也得用啊，不然白学了。我得时常发发牢骚才行，不然我要崩溃
掉了。
