#+TITLE: build a personal website on github
#+SETUPFILE: ../css/level-1.css 
* Register github and creat repos
First you need a [[http://github.com][GitHub]] account. My account name is /digdig/. In order to creat
a website, we follow the instructions on [[http://pages.github.com][GitHub Pages]]. You need to creat a repo
to store your html files. The repo for storing your webpages is *Given* and
*Must* be /username.github.io/. For me, it is just /digdig.github.io/.
* Clone to local and add html files
When you have such a repo, you need to clone it to your local folder:
#+BEGIN_SRC sh
cd ~/Documents    #this is the place I want to put my webpages
git clone https://github.com/digdig/digdig.github.io
#+END_SRC
Now you can see you have a local folder called digdig.github.io
* Push to github
Now copy all of your html files to this folder, the navigation file Must be
called: =index.html=. Run the following command to upload your webpages:
#+BEGIN_SRC sh
cd digdig.github.io
git add . #add all the files in the folder
git commit -m "first upload"
git push
#+END_SRC
Now you have a personal website, its address is very easy to remmeber:
digdig.github.io . No ads, no fee, just cool, isn't it?
* Change the publish setup for future convenience
Now you should change your org-publish setup, change the publish directory to
your local repo =digdig.github.io=. Don't forget to change you root org index file
name to =index.org=.
* Upload your source org code to github
You may also want to upload your org source code to GitHub. It will be no
different with what we have mentioned above. That is:
+ creat a repo
+ clone to the local
+ copy the source codes to that folder
+ push to the web

However, if we don't want to move our source code to another folder. We also
have a way.
** Creat a repo on website
Go to the GitHub website and creat a repo to store your source code, the name of
the repo can be arbitary. I call it: /org-notes/.
** Set up git and commit the local folder
*** Setup your git for the first time
#+BEGIN_SRC sh
git config --global user.name "Your Name Here" #name is arbitary
git confit --global user.email "Your email here" #must be github registration email
#+END_SRC
*** Add and commmit your souce code file
My souce code file is in folder =~/Documents/org/notes/=. The following is to
add and commit your source code in that folder.
#+BEGIN_SRC sh
cd ~/Documents/org/notes/
git init     #create local git repo, so that other git commands can apply
git add .    #add all the files, let git know these files
git commit -m "some message your writ here"  #commit them
#+END_SRC
** Connect local and GitHub
Let the git know you have a GitHub repository
#+BEGIN_SRC sh
git remote add origin https://github.com/digdig/org-notes.git
#+END_SRC
You can confirm this git repository by using:
#+BEGIN_SRC sh
git remote -v
#+END_SRC
Finally you can push all your souce code to GitHub:
#+BEGIN_SRC sh
git push
#+END_SRC
* Using =git fetch= to sync local and server
I encountered this situation: sometimes I delete the local publish folder by
mistake, when I restore it from the [[http://jianguoyun.com][Nutstore]], but can't upload it to git server
any more. The way I fix this is as follow:
+ init the publish folder
+ add remote repo
+ git fetch
+ git add commit and push
